[package]
name = "grilme99/playfab-multiplayer"
description = "API methods for managing multiplayer servers. API methods for managing parties. The lobby service helps players group together to play multiplayer games. It is often used as a rendezvous point for players to share connection information.. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220926.1"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
