[package]
name = "grilme99/playfab-authentication"
description = "The Authentication APIs provide a convenient way to convert classic authentication responses into entity authentication models. These APIs will provide you with the entity authentication token needed for subsequent Entity API calls. Manage API keys for authenticating any entity. The game_server API is designed to create uniquely identifiable game_server entities. The game_server Entity token can be used to call Matchmaking Lobby and Pubsub for server scenarios.. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220908.0"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
